name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macos_build:
    runs-on: macOS-12
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup the build
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Build
        working-directory: build
        run: cmake --build . --config Release -j 4

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: RAVE_VST_MacOS
          path: build/rave-vst_artefacts/Release

